apiVersion: v2
name: iam-auth-proxy
description: Helm chart for deploying an OAuth2 proxy authenticated against INDIGO IAM (or any OIDC-compliant IdP)
type: application
keywords:
  - sso
  - oidc
  - authentication
  - indigo-iam
  - oauth2-proxy
sources:
  - https://github.com/oauth2-proxy/oauth2-proxy
maintainers:
  - email: giorgio.ravelli66@gmail.com
    name: Giovanni Guerrieri

version: 0.1.0
appVersion: "v7.6.0"
