{{- if not .Values.oidc.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iam-auth-proxy.fullname" . }}
  labels:
    {{- include "iam-auth-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  issuer-url: {{ .Values.oidc.issuerURL | b64enc }}
  client-id: {{ .Values.oidc.clientID | b64enc }}
  client-secret: {{ .Values.oidc.clientSecret | b64enc }}
  cookie-secret: {{ include "iam-auth-proxy.cookieSecret" . }}
{{- end -}}
