{{- if not .Values.oidc.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iam-auth-proxy.fullname" . }}
  labels:
    {{- include "iam-auth-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  issuerURL: {{ .Values.oidc.issuerURL | b64enc }}
  clientID: {{ .Values.oidc.clientID | b64enc }}
  clientSecret: {{ .Values.oidc.clientSecret | b64enc }}
  suggestedCookieSecret: {{ include "iam-auth-proxy.cookieSecret" . }}
{{- end -}}
